# COMMENT-HEADER
# File: nyondo/migrations/0001_initial.py
# Simple review note: use this file for code logic and Django app behavior.
# Generated by Django 6.0.4 on 2026-05-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sold', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('quantity_sold', models.PositiveIntegerField()),
                ('receipt_number', models.PositiveBigIntegerField(unique=True)),
                ('payment_method', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('product_code', models.PositiveIntegerField(unique=True)),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('building', 'Building')], max_length=25)),
                ('quantity', models.PositiveIntegerField()),
                ('buying_price', models.PositiveBigIntegerField()),
                ('selling_price', models.PositiveBigIntegerField()),
            ],
        ),
    ]
