# Generated by Django 6.0.4 on 2026-05-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('NIN', models.TextField(blank=True, max_length=50, null=True)),
                ('contact', models.IntegerField()),
                ('signature', models.CharField(blank=True, max_length=100, null=True)),
                ('deposit_amount', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('total_balance', models.IntegerField()),
            ],
        ),
    ]
