# COMMENT-HEADER
# File: nyondo/migrations/0003_credit_signup_stock_date_alter_sale_quantity_sold_and_more.py
# Simple review note: use this file for code logic and Django app behavior.
# Generated by Django 6.0.4 on 2026-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0002_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity_sold',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='receipt_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='buying_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='selling_price',
            field=models.IntegerField(),
        ),
    ]
