# Generated by Django 6.0.4 on 2026-05-16 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0003_credit_signup_stock_date_alter_sale_quantity_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='receipt_number',
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('issued_on', models.DateTimeField(auto_now_add=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='nyondo.sale')),
            ],
        ),
    ]
