# COMMENT-HEADER
# File: nyondo/migrations/0005_sale_specification_stock_specification_and_more.py
# Simple review note: use this file for code logic and Django app behavior.
# Generated by Django 6.0.4 on 2026-05-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0004_remove_sale_receipt_number_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='specification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='specification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_sold',
            field=models.CharField(choices=[('cement', 'Cement'), ('iron_bars', 'Iron Bars'), ('nails', 'Nails'), ('wheelbarrows', 'Wheelbarrows'), ('wire_mesh', 'Wire Mesh'), ('barbed_wire', 'Barbed Wire'), ('iron_sheets', 'Iron Sheets')], max_length=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_name',
            field=models.CharField(choices=[('cement', 'Cement'), ('iron_bars', 'Iron Bars'), ('nails', 'Nails'), ('wheelbarrows', 'Wheelbarrows'), ('wire_mesh', 'Wire Mesh'), ('barbed_wire', 'Barbed Wire'), ('iron_sheets', 'Iron Sheets')], max_length=25),
        ),
    ]
