# Generated by Django 6.0.3 on 2026-05-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0005_sale_specification_stock_specification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_company', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.CharField(choices=[('cement', 'Cement'), ('iron_bars', 'Iron Bars'), ('nails', 'Nails'), ('wheelbarrows', 'Wheelbarrows'), ('wire_mesh', 'Wire Mesh'), ('barbed_wire', 'Barbed Wire'), ('iron_sheets', 'Iron Sheets')], max_length=25)),
                ('specification', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateField()),
                ('is_credit', models.BooleanField(default=False)),
                ('amount_owed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Pending', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
