# Generated by Django 6.0.3 on 2026-05-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0006_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
