# Generated by Django 6.0.4 on 2026-05-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0007_alter_supplier_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='unit_cost',
        ),
        migrations.AddField(
            model_name='supplier',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
