# COMMENT-HEADER
# File: nyondo/migrations/0010_alter_supplier_amount_owed_alter_supplier_deposit_and_more.py
# Simple review note: use this file for code logic and Django app behavior.
# Generated by Django 6.0.3 on 2026-05-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0009_supplierpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='amount_owed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='deposit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='selling_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
