# COMMENT-HEADER
# File: nyondo/migrations/0011_customer.py
# Simple review note: use this file for code logic and Django app behavior.
# Generated by Django 6.0.3 on 2026-05-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0010_alter_supplier_amount_owed_alter_supplier_deposit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('NIN', models.CharField(blank=True, max_length=50, null=True)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('bought_on_credit', models.BooleanField(default=False)),
            ],
        ),
    ]
