# Generated by Django 6.0.4 on 2026-05-20 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0011_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='signature',
        ),
        migrations.AddField(
            model_name='deposit',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nyondo.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='item',
            field=models.CharField(choices=[('cement', 'Cement'), ('iron_sheets', 'Iron Sheets'), ('iron_bars', 'Iron Bars')], default='cement', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='NIN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='receipt_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='total_balance',
            field=models.PositiveIntegerField(),
        ),
    ]
