# COMMENT-HEADER
# File: nyondo/migrations/0013_customer_payment_tracker.py
# Simple review note: use this file for code logic and Django app behavior.
# Generated by Django 6.0.3 on 2026-05-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0012_remove_deposit_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='nyondo.customer')),
            ],
        ),
    ]
