# COMMENT-HEADER
# File: nyondo/migrations/0014_sale_customer_depositpayment.py
# Simple review note: use this file for code logic and Django app behavior.
# Generated by Django 6.0.4 on 2026-05-21 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0013_customer_payment_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='nyondo.customer'),
        ),
        migrations.CreateModel(
            name='DepositPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='nyondo.deposit')),
            ],
        ),
    ]
