# COMMENT-HEADER
# File: nyondo/migrations/0015_customer_address_distance_sale_transport_cost.py
# Simple review note: use this file for code logic and Django app behavior.
# Generated by Django 6.0.4 on 2026-05-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0014_sale_customer_depositpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_distance',
            field=models.PositiveIntegerField(blank=True, help_text='Distance from store in km', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='transport_cost',
            field=models.PositiveIntegerField(default=30000),
        ),
    ]
