# COMMENT-HEADER
# File: nyondo/migrations/0016_sale_delivery.py
# Simple review note: use this file for code logic and Django app behavior.
# Generated by Django 6.0.3 on 2026-05-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0015_customer_address_distance_sale_transport_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
