# Generated by Django 6.0.3 on 2026-05-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0016_sale_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositPaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_receipt_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_nin', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=200, null=True)),
                ('deposit_receipt_number', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('amount_paid', models.PositiveIntegerField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(default='Cash', max_length=100)),
                ('balance_before_payment', models.PositiveIntegerField()),
                ('balance_after_payment', models.PositiveIntegerField()),
                ('total_deposit_amount', models.PositiveIntegerField()),
                ('total_balance_owed', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('issued_by', models.CharField(default='System', max_length=100)),
                ('deposit_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='nyondo.depositpayment')),
            ],
        ),
    ]
