# Generated by Django 6.0.4 on 2026-05-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0019_supplierreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='NIN',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
