# Generated by Django 6.0.4 on 2026-05-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0020_alter_customer_nin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product_code',
        ),
    ]
